[package]
name = "substratee-contract"
version = "1.0.0"
authors = ["Supercomputing Systems"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }
pwasm-utils = { version = "0.6.1", default-features = false }
parity-codec = { version = "3.3", default-features = false, features = ["derive"] }
parity-wasm = { version = "0.31", default-features = false }
wasmi-validation = { version = "0.1", default-features = false }
substrate-primitives = { git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
runtime-primitives = { package = "sr-primitives", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
runtime-io = { package = "sr-io", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
#rstd = { package = "sr-std", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
sandbox = { package = "sr-sandbox", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
srml-support = {git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
system = { package = "srml-system", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
timestamp = { package = "srml-timestamp", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature", default-features = false }
sgx_tstd = { git = "https://github.com/baidu/rust-sgx-sdk" }

[dev-dependencies]
wabt = "~0.7.4"
assert_matches = "1.1"
hex-literal = "0.2.0"
consensus = { package = "srml-consensus", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature" }
balances = { package = "srml-balances", git = "https://github.com/brenzi/substrate.git", branch="global-allocator-feature" }

[features]
default = ["std"]
core = [
	"wasmi-validation/core",
]
std = [
	"serde",
	"parity-codec/std",
	"substrate-primitives/std",
	"runtime-primitives/std",
	"runtime-io/std",
#	"rstd/std",
	"sandbox/std",
	"srml-support/std",
	"system/std",
	"timestamp/std",
	"parity-wasm/std",
	"pwasm-utils/std",
	"wasmi-validation/std",
]
